server:
  port: ${APP_PORT:9090}
  servlet:
    context-path: /news
  compression:
    enabled: true
    min-response-size: 1024
  forward-headers-strategy : framework

spring:
  application:
    name: news
  banner:
    location: classpath:banner.txt
  profiles:
    active: ${PROFILE:local,dev}
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:9000}/${POSTGRES_DB:news}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:1xylixmaF7b7rTYqqQ2Q}
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  liquibase:
    enabled: ${DATABASE_MIGRATION:true}
    change-log: classpath:db/db.changelog.yaml

application:
  configuration:
    cors-allowed-list:
      -  http://localhost:6555
      -  ${PORTAL_URL:http://localhost:8080}
      -  ${API_URL:http://localhost:9090}
    public-api-list:
      - /api/public/**

logging:
  level:
    root: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %thread ${PID} [%X{correlationId}] %-5level %logger{36} - %class{1} - %msg%n"